### PR TITLE
`errors-only` flag and collect errors from Igor

### LINKED ISSUE #10: `–quiet` / `--errors-only` flag or similar that only outputs error
Useful to feed only build/runtime errors to an LLM, asking for help, e.g. `gm run --errors-only | claude`.

We will need support from the runtime to emit structured error messages that we can capture. See thread: https://opera.slack.com/archives/C0ANG36SU5U/p1775568653117109

Related issue (for compile-time errors) #11.

### LINKED ISSUE #11: Capture and display compilation errors more clearly
In addition to  #10 (which focuses on runtime errors) we want to capture _compile time_ errors. To start, we should add a module to parse the errors emitted during the compilation step in `gm-cli compile/run/package`. 

Likely we will collect this with our custom logger somehow, and at the end, if we fail we can use the collected error(s) to give a more descriptive message instead of writing `actionLog.error("Compilation failed")`.

Here's how the IDE extracts the errors:
https://opera.slack.com/archives/C0ANG36SU5U/p1776077515607239

Context, end of this thread: https://opera.slack.com/archives/C0ANG36SU5U/p1775572239004719?thread_ts=1775568653.117109&cid=C0ANG36SU5U

### PR DESCRIPTION
**Pull request by opera-eadelhult**
Resolves #10  and resolves #11. Just waiting on Igor to be released before we merge

### CODE REVIEW

File: src/common-compile-setup.ts [hunk 1]
```diff
@@ -147,14 +152,16 @@ export async function commonCompileSetup(
...
+  // let igorPath: string;
+  // try {
+  //   igorPath = await downloadIgor(ctx, igorLog, cache);
+  // } catch (e) {
+  //   igorLog.error("Failed to download Igor");
+  //   throw new KnownError(e);
+  // }
+  // igorLog.success("Igor downloaded");
+  const igorPath =
+    "/Users/eli/dev/GameMaker/Zeus/Igor/bin/Debug/net8.0/osx-arm64/publish/Igor";
```
Comment (opera-eadelhult) [inline src/common-compile-setup.ts]: Revert this, before merging! Once a new Igor is live
